# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: true
bioc_required: true

apt_packages:
 - libnetcdf-dev
 - udunits-bin
 - libudunits2-dev
 - netcdf-bin

r_github_packages:
 - thomasp85/patchwork

notifications:
    email:
    on_success: change
    on_failure: change