language: R
sudo: true
cache: packages
warnings_are_errors: true
bioc_required: true

r:
  - release
  - devel
  
apt_packages:
- libnetcdf-dev
- udunits-bin
- libudunits2-dev
- netcdf-bin
r_github_packages:
- thomasp85/patchwork

notifications:
  slack:
    rooms:
      secure: Rqt3DlGw4m6dt1jiMVo0vrnTQPd0zSPS7UxnUXKG6q7wLH9SaKzUMOuldq3UL/PnEIfiUnOv/YkLmt2/LMQoPCxfndrExR7gFh993DhBLK5u+N53YzQgfqFQ5cWq/f8JLp3TLfkShOcat8ZR8azMaNHI2mx0VpQX3MRKyNpPzrj7jKOLecfIC+/etW3z2oPkKci9vUXRhelr9+m2g4h5bTSPirwyHiN87STuo9YTYelva9gIx9XSo6bIN5ZTafeNcU3bG8nEhpamUnuN5eJ9+sP3H5uldbLq39vjuGFT9u784SimT7P26rdX4U0OganJRdN2FjmQf7iBlwl+c95rb75shecUJuo/Wy513MJaBrhbdA/plIC21FCRQC7llCqzTjAnqTVeBIl3vE6yUQap0k0qtmmpWm3PJns6JKMdlNgJ0vpnktFY2IAIDqBjIUFhPkO3hbKkxB4sCOsZDWm9cxjmaC0sW+exSofaYOJWMyS79w0RDaFzo4ngEc6yfa1szv5ao8AED1Nby3w9F3jCSPvSD26v3VcD7kgbTwMQru3hpt0sg4nJr79vWkBiTdCNs/sPrUsRTc/8LyPiftlimAyJI0nOjDM/g1Y6Bq7vkxIZD2uWWUbwMrSDiSw7To1vqQbKC4ibgy7q9SZBVBAVay9vIMOv+zEEL0DgJ37qddo=
  on_success: change
  on_failure: change
  email: false